/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as PointsTableRouteImport } from './routes/points-table'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FixturesRouteImport } from './routes/fixtures'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamsIndexRouteImport } from './routes/teams/index'
import { Route as TeamsTeamIdRouteImport } from './routes/teams/$teamId'

const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const PointsTableRoute = PointsTableRouteImport.update({
  id: '/points-table',
  path: '/points-table',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FixturesRoute = FixturesRouteImport.update({
  id: '/fixtures',
  path: '/fixtures',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsIndexRoute = TeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamIdRoute = TeamsTeamIdRouteImport.update({
  id: '/teams/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fixtures': typeof FixturesRoute
  '/gallery': typeof GalleryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/points-table': typeof PointsTableRoute
  '/rules': typeof RulesRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/teams/': typeof TeamsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fixtures': typeof FixturesRoute
  '/gallery': typeof GalleryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/points-table': typeof PointsTableRoute
  '/rules': typeof RulesRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/teams': typeof TeamsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fixtures': typeof FixturesRoute
  '/gallery': typeof GalleryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/points-table': typeof PointsTableRoute
  '/rules': typeof RulesRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/teams/': typeof TeamsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fixtures'
    | '/gallery'
    | '/leaderboard'
    | '/points-table'
    | '/rules'
    | '/teams/$teamId'
    | '/teams/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/fixtures'
    | '/gallery'
    | '/leaderboard'
    | '/points-table'
    | '/rules'
    | '/teams/$teamId'
    | '/teams'
  id:
    | '__root__'
    | '/'
    | '/fixtures'
    | '/gallery'
    | '/leaderboard'
    | '/points-table'
    | '/rules'
    | '/teams/$teamId'
    | '/teams/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FixturesRoute: typeof FixturesRoute
  GalleryRoute: typeof GalleryRoute
  LeaderboardRoute: typeof LeaderboardRoute
  PointsTableRoute: typeof PointsTableRoute
  RulesRoute: typeof RulesRoute
  TeamsTeamIdRoute: typeof TeamsTeamIdRoute
  TeamsIndexRoute: typeof TeamsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/points-table': {
      id: '/points-table'
      path: '/points-table'
      fullPath: '/points-table'
      preLoaderRoute: typeof PointsTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fixtures': {
      id: '/fixtures'
      path: '/fixtures'
      fullPath: '/fixtures'
      preLoaderRoute: typeof FixturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/': {
      id: '/teams/'
      path: '/teams'
      fullPath: '/teams/'
      preLoaderRoute: typeof TeamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId': {
      id: '/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof TeamsTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FixturesRoute: FixturesRoute,
  GalleryRoute: GalleryRoute,
  LeaderboardRoute: LeaderboardRoute,
  PointsTableRoute: PointsTableRoute,
  RulesRoute: RulesRoute,
  TeamsTeamIdRoute: TeamsTeamIdRoute,
  TeamsIndexRoute: TeamsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
